jobs:
- name: fetch-secrets
  plan:
  - task: fetch-secrets-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: /bin/sh
        args:
        - -c
        - |
          apk add --no-cache curl jq bash
          /concourse-scripts/getappdata.sh