resources:
  - name: getappdata
    type: git
    source:
      uri: "https://github.com/SamuraiDaito/Concourse.git"
      branch: main

jobs:
  - name: fetch-secrets-and-run-script
    plan:
      - get: getappdata
        trigger: true

      - task: fetch-secrets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/vault
              tag: latest
          run:
            path: sh
            args:
              - -c
              - |
                # Set Vault address and token
                export VAULT_ADDR='http://192.168.3.109:8200'
                export VAULT_TOKEN='abcd1234'
               
                # Fetch secrets from Vault
                id=$(vault kv get -field=id secret/myapp)
                password=$(vault kv get -field=password secret/myapp)

                # Debugging: Print the secrets
                echo "ID: $id"
                echo "PASSWORD: $password"
