jobs:
  - name: fetch-secrets-and-run-script
    plan:
      - get: getappdata
        trigger: true

      - task: fetch-secrets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/vault
              tag: latest
          outputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Set Vault address and token
                export VAULT_ADDR='http://192.168.3.109:8200'
                export VAULT_TOKEN='abcd1234'
               
                # Fetch secrets from Vault
                Email=$(vault kv get -field=Email secret/screener)
                Password=$(vault kv get -field=Password secret/screener)

                # Store secrets in a file
                echo "Email=$Email" > secrets-output/secrets.env
                echo "Password=$Password" >> secrets-output/secrets.env

                # Print the secrets
                echo "Email: $Email"
                echo "Password: $Password"

      - task: login-to-screener
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Update apk and check if curl and awk are available
                apk update
                apk add --no-cache curl awk

                # Source the secrets file
                source secrets-output/secrets.env

                # Login with multipart form data
                curl -k -X POST \
                  -c cookies.txt \
                  -H 'Content-Type: multipart/form-data' \
                  "https://www.screener.in/login/" \
                  -F "email=$Email" \
                  -F "password=$Password"
