resources:
  - name: getappdata
    type: git
    source:
      uri: "https://github.com/SamuraiDaito/Concourse.git"
      branch: main

jobs:
  - name: fetch-secrets-and-run-script
    plan:
      - get: getappdata
        trigger: true

      - task: fetch-secrets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/vault
              tag: latest
          outputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Set Vault address and token
                export VAULT_ADDR='http://192.168.3.109:8200'
                export VAULT_TOKEN='abcd1234'
               
                # Fetch secrets from Vault
                Email=$(vault kv get -field=Email secret/screener)
                Password=$(vault kv get -field=Password secret/screener)

                # Store secrets in a file
                echo "Email=$Email" > secrets-output/secrets.env
                echo "Password=$Password" >> secrets-output/secrets.env

                # Print the secrets
                echo "Email: $Email"
                echo "Password: $Password"

      - task: login-to-screener
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Install curl
                apk add --no-cache curl
                
                # Source the secrets file
                source secrets-output/secrets.env
                
                # Step 1: Fetch CSRF Token
                csrf_token=$(curl -s -c cookies.txt "https://www.screener.in/login/" | grep -oP 'name="csrf_token" value="\K[^"]+')
                
                # Step 2: Perform login with CSRF Token
                curl -k -X POST \
                  -b cookies.txt \
                  -c cookies.txt \
                  -H 'Content-Type: multipart/form-data' \
                  -F "username=$Email" \
                  -F "password=$Password" \
                  -F "csrf_token=$csrf_token" \
                  "https://www.screener.in/login/" \
                  -v
