resources:
  - name: getappdata
    type: git
    source:
      uri: "https://github.com/SamuraiDaito/Concourse.git"
      branch: main

jobs:
  - name: fetch-secrets-and-run-script
    plan:
      - get: getappdata
        trigger: true

      - task: fetch-secrets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/vault
              tag: latest
          outputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Set Vault address and token
                export VAULT_ADDR='http://0.0.0.0:8200'
                export VAULT_TOKEN='abcd1234
               
                # Fetch secrets from Vault
                username=$(vault kv get -field=username secret/data/myapp)
                password=$(vault kv get -field=password secret/data/myapp)
 
                # Store secrets in a file
                echo "export USERNAME=$username" > secrets-output/secrets.sh
                echo "export PASSWORD=$password" >> secrets-output/secrets.sh
                chmod +x secrets-output/secrets.sh
 
                # Debugging: List the contents of the secrets directory
                echo "Contents of secrets-output directory:"
                ls -l secrets-output
 
                # Debugging: Print the contents of the secrets file
                echo "Contents of secrets.sh:"
                cat secrets-output/secrets.sh

      - task: run-appdata-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: getappdata
          run:
            path: sh
            args:
              - -c
              - |
                # Make sure the script is executable
                chmod +x getappdata/getappdata.sh
                # Run the script
                ./getappdata.sh
