resources:
- name: getappdata-repo
  type: git
  source:
    uri: https://github.com/SamuraiDaito/Concourse.git
    branch: main

jobs:
- name: fetch-secrets
  plan:
  - get: getappdata-repo
    trigger: true
  - task: fetch-secrets-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: /bin/sh
        args:
        - -c
        - |
          apk add --no-cache curl jq bash
          chmod +x getappdata-repo/getappdata.sh
          ./getappdata-repo/getappdata.sh
