resources:
  - name: getappdata
    type: git
    source:
      uri: "https://github.com/SamuraiDaito/Concourse.git"
      branch: main

jobs:
  - name: fetch-secrets-and-run-script
    plan:
      - get: getappdata
        trigger: true

      - task: fetch-secrets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/vault
              tag: latest
          outputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Set Vault address and token
                export VAULT_ADDR='http://192.168.3.109:8200'
                export VAULT_TOKEN='abcd1234'
               
                # Fetch secrets from Vault
                Email=$(vault kv get -field=Email secret/screener)
                Password=$(vault kv get -field=Password secret/screener)

                # Store secrets in a file
                echo "Email=$Email" > secrets-output/secrets.env
                echo "Password=$Password" >> secrets-output/secrets.env

                # Print the secrets
                echo "Email: $Email"
                echo "Password: $Password"

      - task: login-to-screener
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Install curl and awk
                apk update && apk add --no-cache curl awk

                # Source the secrets file
                source secrets-output/secrets.env

                # Fetch login page to get CSRF token
                csrf_token=$(curl -s https://www.screener.in/login/ | awk -F'csrf_token' '{print $2}' | awk -F'value="' '{print $2}' | awk -F'"' '{print $1}')

                # Login with CSRF token and credentials
                curl -X POST https://www.screener.in/login/ \
                  -d "email=$Email" \
                  -d "password=$Password" \
                  -d "csrf_token=$csrf_token" \
                  -c cookies.txt \
                  -v
